version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stack-name"
s3_bucket = "bucket-name"
s3_prefix = "your-bucket"
region = "us-east-1"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
